<?php

namespace App\Model\FIT;

// TODO: Should this be called FITProfile or Profile?
// TODO: Not certain, but I think this is a global profile and device profiles are merged with this for reading and writing data.See SDK.
class FITProfile
{

  public static function fitEnumToString($type, $value)
  {
    $enum_data = self::fitEnumData();
    return isset($enum_data[$type][$value]) ? $enum_data[$type][$value] : 'unknown';
  }

  /**
   * Returns an array of enum data as specified by the FIT SDK. Taken from adriangibbons/php-fit-file-analysis.
   * TODO: write script to extract enum data from excel file provided in the SDK.
   *
   * @return array enum data
   */
  public static function fitEnumData()
  {
    return [
      'activity' => [
					0 => 'manual',
					1 => 'auto_multi_sport',
				],
      'ant_network' => [
					0 => 'public',
					1 => 'antplus',
					2 => 'antfs',
					3 => 'private',
			],
      'battery_status' => [
					1 => 'new',
					2 => 'good',
					3 => 'ok',
					4 => 'low',
					5 => 'critical',
					7 => 'unknown',
			],
      'body_location' => [
          0 => 'left_leg',
          1 => 'left_calf',
          2 => 'left_shin',
          3 => 'left_hamstring',
          4 => 'left_quad',
          5 => 'left_glute',
          6 => 'right_leg',
          7 => 'right_calf',
          8 => 'right_shin',
          9 => 'right_hamstring',
          10 => 'right_quad',
          11 => 'right_glute',
          12 => 'torso_back',
          13 => 'left_lower_back',
          14 => 'left_upper_back',
          15 => 'right_lower_back',
          16 => 'right_upper_back',
          17 => 'torso_front',
          18 => 'left_abdomen',
          19 => 'left_chest',
          20 => 'right_abdomen',
          21 => 'right_chest',
          22 => 'left_arm',
          23 => 'left_shoulder',
          24 => 'left_bicep',
          25 => 'left_tricep',
          26 => 'left_brachioradialis',
          27 => 'left_forearm_extensors',
          28 => 'right_arm',
          29 => 'right_shoulder',
          30 => 'right_bicep',
          31 => 'right_tricep',
          32 => 'right_brachioradialis',
          33 => 'right_forearm_extensors',
          34 => 'neck',
          35 => 'throat'
      ],
      'display_heart' => [
					0 => 'bpm',
					1 => 'max',
					2 => 'reserve',
			],
      'display_measure' => [
					0 => 'metric',
					1 => 'statute',
			],
      'display_position' => [
          0 => 'degree',                //dd.dddddd
          1 => 'degree_minute',         //dddmm.mmm
          2 => 'degree_minute_second',  //dddmmss
          3 => 'austrian_grid',   //Austrian Grid (BMN)
          4 => 'british_grid',    //British National Grid
          5 => 'dutch_grid',      //Dutch grid system
          6 => 'hungarian_grid',  //Hungarian grid system
          7 => 'finnish_grid',    //Finnish grid system Zone3 KKJ27
          8 => 'german_grid',     //Gausss Krueger (German)
          9 => 'icelandic_grid',  //Icelandic Grid
          10 => 'indonesian_equatorial',  //Indonesian Equatorial LCO
          11 => 'indonesian_irian',       //Indonesian Irian LCO
          12 => 'indonesian_southern',    //Indonesian Southern LCO
          13 => 'india_zone_0',      //India zone 0
          14 => 'india_zone_IA',     //India zone IA
          15 => 'india_zone_IB',     //India zone IB
          16 => 'india_zone_IIA',    //India zone IIA
          17 => 'india_zone_IIB',    //India zone IIB
          18 => 'india_zone_IIIA',   //India zone IIIA
          19 => 'india_zone_IIIB',   //India zone IIIB
          20 => 'india_zone_IVA',    //India zone IVA
          21 => 'india_zone_IVB',    //India zone IVB
          22 => 'irish_transverse',  //Irish Transverse Mercator
          23 => 'irish_grid',        //Irish Grid
          24 => 'loran',             //Loran TD
          25 => 'maidenhead_grid',   //Maidenhead grid system
          26 => 'mgrs_grid',         //MGRS grid system
          27 => 'new_zealand_grid',  //New Zealand grid system
          28 => 'new_zealand_transverse',  //New Zealand Transverse Mercator
          29 => 'qatar_grid',              //Qatar National Grid
          30 => 'modified_swedish_grid',   //Modified RT-90 (Sweden)
          31 => 'swedish_grid',            //RT-90 (Sweden)
          32 => 'south_african_grid',      //South African Grid
          33 => 'swiss_grid',              //Swiss CH-1903 grid
          34 => 'taiwan_grid',             //Taiwan Grid
          35 => 'united_states_grid',      //United States National Grid
          36 => 'utm_ups_grid',            //UTM/UPS grid system
          37 => 'west_malayan',            //West Malayan RSO
          38 => 'borneo_rso',              //Borneo RSO
          39 => 'estonian_grid',           //Estonian grid system
          40 => 'latvian_grid',            //Latvian Transverse Mercator
          41 => 'swedish_ref_99_grid',     //Reference Grid 99 TM (Swedish)
      ],
      'display_power' => [
					0 => 'watts',
					1 => 'percent_ftp',
			],
      'event' => [
          0 => 'timer',
          3 => 'workout',
          4 => 'workout_step',
          5 => 'power_down',
          6 => 'power_up',
          7 => 'off_course',
          8 => 'session',
          9 => 'lap',
          10 => 'course_point',
          11 => 'battery',
          12 => 'virtual_partner_pace',
          13 => 'hr_high_alert',
          14 => 'hr_low_alert',
          15 => 'speed_high_alert',
          16 => 'speed_low_alert',
          17 => 'cad_high_alert',
          18 => 'cad_low_alert',
          19 => 'power_high_alert',
          20 => 'power_low_alert',
          21 => 'recovery_hr',
          22 => 'battery_low',
          23 => 'time_duration_alert',
          24 => 'distance_duration_alert',
          25 => 'calorie_duration_alert',
          26 => 'activity',
          27 => 'fitness_equipment',
          28 => 'length',
          32 => 'user_marker',
          33 => 'sport_point',
          36 => 'calibration',
          42 => 'front_gear_change',
          43 => 'rear_gear_change',
          44 => 'rider_position_change',
          45 => 'elev_high_alert',
          46 => 'elev_low_alert',
          47 => 'comm_timeout'
      ],
      'event_type' => [
          0 => 'start',
          1 => 'stop',
          2 => 'consecutive_depreciated',
          3 => 'marker',
          4 => 'stop_all',
          5 => 'begin_depreciated',
          6 => 'end_depreciated',
          7 => 'end_all_depreciated',
          8 => 'stop_disable',
          9 => 'stop_disable_all'
      ],
      'file' => [
          1 => 'device',
          2 => 'settings',
          3 => 'sport',
          4 => 'activity',
          5 => 'workout',
          6 => 'course',
          7 => 'schedules',
          9 => 'weight',
          10 => 'totals',
          11 => 'goals',
          14 => 'blood_pressure',
          15 => 'monitoring_a',
          20 => 'activity_summary',
          28 => 'monitoring_daily',
          32 => 'monitoring_b',
          0xF7 => 'mfg_range_min',
          0xFE => 'mfg_range_max'
      ],
      'gender' => [
					0 => 'female',
					1 => 'male',
			],
      'hr_zone_calc' => [
					0 => 'custom',
					1 => 'percent_max_hr',
					2 => 'percent_hrr',
			],
      'intensity' => [
					0 => 'active',
					1 => 'rest',
					2 => 'warmup',
					3 => 'cooldown',
			],
      'language' => [
          0 => 'english',
          1 => 'french',
          2 => 'italian',
          3 => 'german',
          4 => 'spanish',
          5 => 'croatian',
          6 => 'czech',
          7 => 'danish',
          8 => 'dutch',
          9 => 'finnish',
          10 => 'greek',
          11 => 'hungarian',
          12 => 'norwegian',
          13 => 'polish',
          14 => 'portuguese',
          15 => 'slovakian',
          16 => 'slovenian',
          17 => 'swedish',
          18 => 'russian',
          19 => 'turkish',
          20 => 'latvian',
          21 => 'ukrainian',
          22 => 'arabic',
          23 => 'farsi',
          24 => 'bulgarian',
          25 => 'romanian',
          254 => 'custom'
      ],
      'length_type' => [
					0 => 'idle',
					1 => 'active',
			],
      'manufacturer' => [  // Have capitalised select manufacturers
          1 => 'Garmin',
          2 => 'garmin_fr405_antfs',
          3 => 'zephyr',
          4 => 'dayton',
          5 => 'idt',
          6 => 'SRM',
          7 => 'Quarq',
          8 => 'iBike',
          9 => 'saris',
          10 => 'spark_hk',
          11 => 'Tanita',
          12 => 'Echowell',
          13 => 'dynastream_oem',
          14 => 'nautilus',
          15 => 'dynastream',
          16 => 'Timex',
          17 => 'metrigear',
          18 => 'xelic',
          19 => 'beurer',
          20 => 'cardiosport',
          21 => 'a_and_d',
          22 => 'hmm',
          23 => 'Suunto',
          24 => 'thita_elektronik',
          25 => 'gpulse',
          26 => 'clean_mobile',
          27 => 'pedal_brain',
          28 => 'peaksware',
          29 => 'saxonar',
          30 => 'lemond_fitness',
          31 => 'dexcom',
          32 => 'Wahoo Fitness',
          33 => 'octane_fitness',
          34 => 'archinoetics',
          35 => 'the_hurt_box',
          36 => 'citizen_systems',
          37 => 'Magellan',
          38 => 'osynce',
          39 => 'holux',
          40 => 'concept2',
          42 => 'one_giant_leap',
          43 => 'ace_sensor',
          44 => 'brim_brothers',
          45 => 'xplova',
          46 => 'perception_digital',
          47 => 'bf1systems',
          48 => 'pioneer',
          49 => 'spantec',
          50 => 'metalogics',
          51 => '4iiiis',
          52 => 'seiko_epson',
          53 => 'seiko_epson_oem',
          54 => 'ifor_powell',
          55 => 'maxwell_guider',
          56 => 'star_trac',
          57 => 'breakaway',
          58 => 'alatech_technology_ltd',
          59 => 'mio_technology_europe',
          60 => 'Rotor',
          61 => 'geonaute',
          62 => 'id_bike',
          63 => 'Specialized',
          64 => 'wtek',
          65 => 'physical_enterprises',
          66 => 'north_pole_engineering',
          67 => 'BKOOL',
          68 => 'Cateye',
          69 => 'Stages Cycling',
          70 => 'Sigmasport',
          71 => 'TomTom',
          72 => 'peripedal',
          73 => 'Wattbike',
          76 => 'moxy',
          77 => 'ciclosport',
          78 => 'powerbahn',
          79 => 'acorn_projects_aps',
          80 => 'lifebeam',
          81 => 'Bontrager',
          82 => 'wellgo',
          83 => 'scosche',
          84 => 'magura',
          85 => 'woodway',
          86 => 'elite',
          87 => 'nielsen_kellerman',
          88 => 'dk_city',
          89 => 'Tacx',
          90 => 'direction_technology',
          91 => 'magtonic',
          92 => '1partcarbon',
          93 => 'inside_ride_technologies',
          94 => 'sound_of_motion',
          95 => 'stryd',
          96 => 'icg',
          97 => 'MiPulse',
          98 => 'bsx_athletics',
          99 => 'look',
          100 => 'campagnolo_srl',
          101 => 'body_bike_smart',
          102 => 'praxisworks',
          103 => 'limits_technology',
          104 => 'topaction_technology',
          105 => 'cosinuss',
          106 => 'fitcare',
          107 => 'magene',
          108 => 'giant_manufacturing_co',
          109 => 'tigrasport',
          110 => 'salutron',
          111 => 'technogym',
          112 => 'bryton_sensors',
          113 => 'latitude_limited',
          114 => 'soaring_technology',
          115 => 'igpsport',
          116 => 'thinkrider',
          117 => 'gopher_sport',
          118 => 'waterrower',
          119 => 'orangetheory',
          120 => 'inpeak',
          121 => 'kinetic',
          122 => 'johnson_health_tech',
          123 => 'polar_electro',
          124 => 'seesense',
          125 => 'nci_technology',
          126 => 'iqsquare',
          127 => 'leomo',
          128 => 'ifit_com',
          255 => 'development',
          257 => 'healthandlife',
          258 => 'Lezyne',
          259 => 'scribe_labs',
          260 => 'Zwift',
          261 => 'watteam',
          262 => 'recon',
          263 => 'favero_electronics',
          264 => 'dynovelo',
          265 => 'Strava',
          266 => 'precor',
          267 => 'Bryton',
          268 => 'sram',
          269 => 'navman',
          270 => 'cobi',
          271 => 'spivi',
          272 => 'mio_magellan',
          273 => 'evesports',
          274 => 'sensitivus_gauge',
          275 => 'podoon',
          276 => 'life_time_fitness',
          277 => 'falco_e_motors',
          278 => 'minoura',
          279 => 'cycliq',
          280 => 'luxottica',
          281 => 'trainer_road',
          282 => 'the_sufferfest',
          283 => 'fullspeedahead',
          284 => 'virtualtraining',
          285 => 'feedbacksports',
          286 => 'omata',
          287 => 'vdo',
          288 => 'magneticdays',
          289 => 'hammerhead',
          290 => 'kinetic_by_kurt',
          291 => 'shapelog',
          292 => 'dabuziduo',
          293 => 'jetblack',
          294 => 'coros',
          295 => 'virtugo',
          296 => 'velosense',
          297 => 'cycligentinc',
          298 => 'trailforks',
          299 => 'mahle_ebikemotion',
          5759 => 'actigraphcorp'
      ],
      'pwr_zone_calc' => [
					0 => 'custom',
					1 => 'percent_ftp',
			],
      'product' => [  // Have formatted for devices known to use FIT format. (Original text commented-out).
          1 => 'hrm1',
          2 => 'axh01',
          3 => 'axb01',
          4 => 'axb02',
          5 => 'hrm2ss',
          6 => 'dsi_alf02',
          7 => 'hrm3ss',
          8 => 'hrm_run_single_byte_product_id',
          9 => 'bsm',
          10 => 'bcm',
          11 => 'axs01',
          12 => 'HRM-Tri',                    // 'hrm_tri_single_byte_product_id',
          14 => 'Forerunner 225',             // 'fr225_single_byte_product_id',
          473 => 'Forerunner 301',            // 'fr301_china',
          474 => 'Forerunner 301',            // 'fr301_japan',
          475 => 'Forerunner 301',            // 'fr301_korea',
          494 => 'Forerunner 301',            // 'fr301_taiwan',
          717 => 'Forerunner 405',            // 'fr405',
          782 => 'Forerunner 50',             // 'fr50',
          987 => 'Forerunner 405',            // 'fr405_japan',
          988 => 'Forerunner 60',             // 'fr60',
          1011 => 'dsi_alf01',
          1018 => 'Forerunner 310XT',         // 'fr310xt',
          1036 => 'Edge 500',                 // 'edge500',
          1124 => 'Forerunner 110',           // 'fr110',
          1169 => 'Edge 800',                 // 'edge800',
          1199 => 'Edge 500',                 // 'edge500_taiwan',
          1213 => 'Edge 500',                 // 'edge500_japan',
          1253 => 'chirp',
          1274 => 'Forerunner 110',           // 'fr110_japan',
          1325 => 'edge200',
          1328 => 'Forerunner 910XT',         // 'fr910xt',
          1333 => 'Edge 800',                 // 'edge800_taiwan',
          1334 => 'Edge 800',                 // 'edge800_japan',
          1341 => 'alf04',
          1345 => 'Forerunner 610',           // 'fr610',
          1360 => 'Forerunner 210',           // 'fr210_japan',
          1380 => 'Vector 2S',                // vector_ss
          1381 => 'Vector 2',                 // vector_cp
          1386 => 'Edge 800',                 // 'edge800_china',
          1387 => 'Edge 500',                 // 'edge500_china',
          1410 => 'Forerunner 610',           // 'fr610_japan',
          1422 => 'Edge 500',                 // 'edge500_korea',
          1436 => 'Forerunner 70',            // 'fr70',
          1446 => 'Forerunner 310XT',         // 'fr310xt_4t',
          1461 => 'amx',
          1482 => 'Forerunner 10',            // 'fr10',
          1497 => 'Edge 800',                 // 'edge800_korea',
          1499 => 'swim',
          1537 => 'Forerunner 910XT',         // 'fr910xt_china',
          1551 => 'Fenix',                    // fenix
          1555 => 'edge200_taiwan',
          1561 => 'Edge 510',                 // 'edge510',
          1567 => 'Edge 810',                 // 'edge810',
          1570 => 'tempe',
          1600 => 'Forerunner 910XT',         // 'fr910xt_japan',
          1623 => 'Forerunner 620',           // 'fr620',
          1632 => 'Forerunner 220',           // 'fr220',
          1664 => 'Forerunner 910XT',         // 'fr910xt_korea',
          1688 => 'Forerunner 10',            // 'fr10_japan',
          1721 => 'Edge 810',                 // 'edge810_japan',
          1735 => 'virb_elite',
          1736 => 'edge_touring',
          1742 => 'Edge 510',                 // 'edge510_japan',
          1743 => 'HRM-Tri',                  // 'hrm_tri',
          1752 => 'hrm_run',
          1765 => 'Forerunner 920XT',         // 'fr920xt',
          1821 => 'Edge 510',                 // 'edge510_asia',
          1822 => 'Edge 810',                 // 'edge810_china',
          1823 => 'Edge 810',                 // 'edge810_taiwan',
          1836 => 'Edge 1000',                // 'edge1000',
          1837 => 'vivo_fit',
          1853 => 'virb_remote',
          1885 => 'vivo_ki',
          1903 => 'Forerunner 15',            // 'fr15',
          1907 => 'vivoactive',               // 'vivo_active',
          1918 => 'Edge 510',                 // 'edge510_korea',
          1928 => 'Forerunner 620',           // 'fr620_japan',
          1929 => 'Forerunner 620',           // 'fr620_china',
          1930 => 'Forerunner 220',           // 'fr220_japan',
          1931 => 'Forerunner 220',           // 'fr220_china',
          1936 => 'Approach S6',              // 'approach_s6'
          1956 => 'vívosmart',                // 'vivo_smart',
          1967 => 'Fenix 2',                  // fenix2
          1988 => 'epix',
          2050 => 'Fenix 3',                  // fenix3
          2052 => 'Edge 1000',                // edge1000_taiwan
          2053 => 'Edge 1000',                // edge1000_japan
          2061 => 'Forerunner 15',            // fr15_japan
          2067 => 'Edge 520',                 // edge520
          2070 => 'Edge 1000',                // edge1000_china
          2072 => 'Forerunner 620',           // fr620_russia
          2073 => 'Forerunner 220',           // fr220_russia
          2079 => 'Vector S',                 // vector_s
          2100 => 'Edge 1000',                // edge1000_korea
          2130 => 'Forerunner 920',           // fr920xt_taiwan
          2131 => 'Forerunner 920',           // fr920xt_china
          2132 => 'Forerunner 920',           // fr920xt_japan
          2134 => 'virbx',
          2135 => 'vívosmart',                // vivo_smart_apac',
          2140 => 'etrex_touch',
          2147 => 'Edge 25',                  // edge25
          2148 => 'Forerunner 25',            // fr25
          2150 => 'vivo_fit2',
          2153 => 'Forerunner 225',           // fr225
          2156 => 'Forerunner 630',           // fr630
          2157 => 'Forerunner 230',           // fr230
          2160 => 'vivo_active_apac',
          2161 => 'Vector 2',                 // vector_2
          2162 => 'Vector 2S',                // vector_2s
          2172 => 'virbxe',
          2173 => 'Forerunner 620',           // fr620_taiwan
          2174 => 'Forerunner 220',           // fr220_taiwan
          2175 => 'truswing',
          2188 => 'Fenix 3',                  // fenix3_china
          2189 => 'Fenix 3',                  // fenix3_twn
          2192 => 'varia_headlight',
          2193 => 'varia_taillight_old',
          2204 => 'Edge Explore 1000',        // edge_explore_1000
          2219 => 'Forerunner 225',           // fr225_asia
          2225 => 'varia_radar_taillight',
          2226 => 'varia_radar_display',
          2238 => 'Edge 20',                  // edge20
          2262 => 'D2 Bravo',                 // d2_bravo
          2266 => 'approach_s20',
          2276 => 'varia_remote',
          2327 => 'hrm4_run',
          2337 => 'vivo_active_hr',
          2347 => 'vivo_smart_gps_hr',
          2348 => 'vivo_smart_hr',
          2368 => 'vivo_move',
          2398 => 'varia_vision',
          2406 => 'vivo_fit3',
          2413 => 'Fenix 3 HR',               // fenix3_hr
          2417 => 'Virb Ultra 30',            // virb_ultra_30
          2429 => 'index_smart_scale',
          2431 => 'Forerunner 235',           // fr235
          2432 => 'Fenix 3 Chronos',          // fenix3_chronos
          2441 => 'oregon7xx',
          2444 => 'rino7xx',
          2496 => 'nautix',
          2530 => 'Edge 820',                 // edge_820
          2531 => 'Edge Explore 820',         // edge_explore_820
          2544 => 'fenix5s',
          2547 => 'D2 Bravo Titanium',        // d2_bravo_titanium
          2593 => 'Running Dynamics Pod',     // running_dynamics_pod
          2604 => 'Fenix 5x',                 // fenix5x
          2606 => 'vivofit jr',               // vivo_fit_jr
          2691 => 'Forerunner 935',           // fr935
          2697 => 'Fenix 5',                  // fenix5
          2700 => 'vivoactive3',
          2769 => 'foretrex_601_701',
          2772 => 'vivo_move_hr',
          2713 => 'Edge 1030',                // edge_1030
          2806 => 'approach_z80',
          2831 => 'vivo_smart3_apac',
          2832 => 'vivo_sport_apac',
          2859 => 'descent',
          2886 => 'Forerunner 645',           // fr645
          2888 => 'Forerunner 645',           // fr645m
          2900 => 'Fenix 5S Plus',            // fenix5s_plus
          2909 => 'Edge 130',                 // Edge_130
          2927 => 'vivosmart_4',
          2962 => 'approach_x10',
          2988 => 'vivoactive3m_w',
          3011 => 'edge_explore',
          3028 => 'gpsmap66',
          3049 => 'approach_s10',
          3066 => 'vivoactive3m_l',
          3085 => 'approach_g80',
          3110 => 'Fenix 5 Plus',             // fenix5_plus
          3111 => 'Fenix 5X Plus',            // fenix5x_plus
          3112 => 'Edge 520 Plus',            // edge_520_plus
          3299 => 'hrm_dual',
          3314 => 'approach_s40',
          10007 => 'SDM4 footpod',            // sdm4
          10014 => 'edge_remote',
          20119 => 'training_center',
          65531 => 'connectiq_simulator',
          65532 => 'android_antplus_plugin',
          65534 => 'Garmin Connect website'   // connect
      ],
      'sport' => [  // Have capitalised and replaced underscores with spaces.
          0 => 'Generic',
          1 => 'Running',
          2 => 'Cycling',
          3 => 'Transition',
          4 => 'Fitness equipment',
          5 => 'Swimming',
          6 => 'Basketball',
          7 => 'Soccer',
          8 => 'Tennis',
          9 => 'American football',
          10 => 'Training',
          11 => 'Walking',
          12 => 'Cross country skiing',
          13 => 'Alpine skiing',
          14 => 'Snowboarding',
          15 => 'Rowing',
          16 => 'Mountaineering',
          17 => 'Hiking',
          18 => 'Multisport',
          19 => 'Paddling',
          254 => 'All'
      ],
      'sub_sport' => [  // Have capitalised and replaced underscores with spaces.
          0 => 'Generic',
          1 => 'Treadmill',
          2 => 'Street',
          3 => 'Trail',
          4 => 'Track',
          5 => 'Spin',
          6 => 'Indoor cycling',
          7 => 'Road',
          8 => 'Mountain',
          9 => 'Downhill',
          10 => 'Recumbent',
          11 => 'Cyclocross',
          12 => 'Hand cycling',
          13 => 'Track cycling',
          14 => 'Indoor rowing',
          15 => 'Elliptical',
          16 => 'Stair climbing',
          17 => 'Lap swimming',
          18 => 'Open water',
          19 => 'Flexibility training',
          20 => 'Strength training',
          21 => 'Warm up',
          22 => 'Match',
          23 => 'Exercise',
          24 => 'Challenge',
          25 => 'Indoor skiing',
          26 => 'Cardio training',
          27 => 'Indoor walking',
          28 => 'E-Bike Fitness',
          254 => 'All'
      ],
      'session_trigger' => [
					0 => 'activity_end',
					1 => 'manual',
					2 => 'auto_multi_sport',
					3 => 'fitness_equipment',
			],
      'source_type' => [
          0 => 'ant',  //External device connected with ANT
          1 => 'antplus',  //External device connected with ANT+
          2 => 'bluetooth',  //External device connected with BT
          3 => 'bluetooth_low_energy',  //External device connected with BLE
          4 => 'wifi',  //External device connected with Wifi
          5 => 'local',  //Onboard device
      ],
      'swim_stroke' => [
					0 => 'Freestyle',
					1 => 'Backstroke',
					2 => 'Breaststroke',
					3 => 'Butterfly',
					4 => 'Drill',
					5 => 'Mixed',
					6 => 'IM'],  // Have capitalised.
      'water_type' => [
					0 => 'fresh',
					1 => 'salt',
					2 => 'en13319',
					3 => 'custom',
			],
      'tissue_model_type' => [
					0 => 'zhl_16c',
			],
      'dive_gas_status' => [
					0 => 'disabled',
					1 => 'enabled',
					2 => 'backup_only',
			],
      'dive_alarm_type' => [
					0 => 'depth',
					1 => 'time',
			],
      'dive_backlight_mode' => [
					0 => 'at_depth',
					1 => 'always_on',
			],
    ];
  }
}
